version: '3'
services:
  frontend:
    image: mern-frontend:1.0
    ports:
      - 3000:3000
  backend:  
    image: mern-backend:1.0
    ports:
      - 5000:5000
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017